### ISSUE TITLE
pyvoicechanger does not install in fedora

### ISSUE THREAD

**Issue by Kazenin** [juancarlospaco/pyvoicechanger#10]
Hello,
I am trying to install but I had this issue:

```
$ sudo pip install pyvoicechanger
Collecting pyvoicechanger
  Using cached https://files.pythonhosted.org/packages/bb/32/a603069d3c0ac05c2dc7bf1168b9ae1b38a3905bcd683ff032bcf4ad4a2d/pyvoicechanger-1.5.0-py2.py3-none-any.whl
pyvoicechanger requires Python '>=3.6' but the running Python is 2.7.14
```
How to run with python 3? I have it installed already

**Comment by juancarlospaco** [comment]
https://github.com/juancarlospaco/pyvoicechanger#requisites
Python **3.6**

Check your version with `python --version`

**Comment by Kazenin** [comment]
good morning

solved with:

```
$ sudo python3.6 -m pip install pyvoicechanger
``` 
If you want to add in readme, I think is interesting.

Thank you
