### ISSUE TITLE
syntax error in code

### ISSUE THREAD

**Issue by yunaranyancat** [juancarlospaco/pyvoicechanger#11]
After running the troubleshoot, I still got the same error.

```
~/Desktop/pyvoicechanger-master$ python3 pyvoicechanger.py
  File "pyvoicechanger.py", line 73
    lambda: self.control.setToolTip(f"<b>{self.control.value()}"))
                                                                                              ^
SyntaxError: invalid syntax
```

**Comment by juancarlospaco** [comment]
https://github.com/juancarlospaco/pyvoicechanger#requisites
Python **3.6**
It uses F-Strings.

**Comment by dmbomer** [comment]
I was successful with the install but when I run the program 

  File "pyvoicechanger.py", line 73
    lambda: self.control.setToolTip(f"<b>{self.control.value()}"))
                                                                                              ^
SyntaxError: invalid syntax

I have multiple versions of python 2, 3.5 3.6 3.7.  

I did the alias to python3 in my .bashrc but nothing I do starts the program.  

sudo apt-get install sox python3-pyqt5 done no issues
sudo pip install pyvoicechanger no issues
pip3 install PyQt5 installed no issues
modprobe snd-aloop no output is returned ALSA is installed on the system and so is pulseaudio

I am at a lost where did I go wrong?

**Comment by juancarlospaco** [comment]
Somehow your system is using Python2 anyways.
Legacy Python is not supported since is going to die soon.
