### ISSUE TITLE
How to send modulated voice to audio conferences?

### ISSUE THREAD

**Issue by Kazenin** [juancarlospaco/pyvoicechanger#12]
I am using discord and my voice is normal to my partners. I hear my voice  changed in loopback (headphones), but does not work in apps

**Comment by juancarlospaco** [comment]
- The App must let you choose other input than Microphone.
- You should choose the Sound Loopback.
- You must have a Working Sound Loopback Kernel Module.

[Check the documentation, execute the commands detailed there.](https://github.com/juancarlospaco/pyvoicechanger#troubleshooting)
