### ISSUE TITLE
[FR] don't auto-hide to system tray

### ISSUE THREAD

**Issue by ITwrx** [juancarlospaco/pyvoicechanger#14]
pyvoicechanger is disappearing into a parallel universe when i use my beloved gnome3 in arch linux. 

I choose one voice modulation setting on the dial, and once it starts playing back, it auto-hides to the "system tray". i don't think i have one of those. :) To me, it would be nice if it didn't hide to anywhere automatically. 

thanks

**Comment by VassiliosUG** [comment]
Open PyVoiceChanger with any text/code editor and find where it says:
`if self.isVisible():
            self.statusBar().showMessage("Minimizing to System TrayIcon", 3000)
            print("Minimizing Main Window to System TrayIcon now...")
            sleep(3)
            self.hide()`
Then all you have to do is put a # in front of self.hide() so your code should look like:
`if self.isVisible():
            self.statusBar().showMessage("Minimizing to System TrayIcon", 3000)
            print("Minimizing Main Window to System TrayIcon now...")
            sleep(3)
            #self.hide()`

**Comment by ITwrx** [comment]
@VassiliosUG thank you very much for the workaround. i'll do that.

**Comment by juancarlospaco** [comment]
Great solution, I didnt know how to make it better, but that works, pull request welcome too, thanks.
:slightly_smiling_face:
