### ISSUE TITLE
Cannot run pyvoicechanger

### ISSUE THREAD

**Issue by yousefvand** [juancarlospaco/pyvoicechanger#15]
Hello

I have installed program but get this error:

```
$ pyvoicechanger.py
File "/home/remisa/.pyenv/versions/3.7.2/bin/pyvoicechanger.py", line 73
    lambda: self.control.setToolTip(f"<b>{self.control.value()}"))
                                                               ^
```

I have Ubuntu 16.04 LTS:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial
```
And installed python via [pyenv](https://github.com/pyenv/pyenv):

```
$ python -V
Python 3.7.2
$ which python
/home/remisa/.pyenv/shims/python
```

Can you help we how to fix this problem?

**Comment by juancarlospaco** [comment]
Have PyQt5 and Sox installed?.

**Comment by yousefvand** [comment]
Yes I have `SoX v14.4.1` and PyQt5 `5.5.1+dfsg-3ubuntu4` installed. The problem is Ubuntu has python `Python 2.7.12` preinstalled so I did install `Python 3.7.3` via `pyenv` but when I use `sudo` it uses `python2` and if I try to run it through `python3` I get the followin error:

```
Traceback (most recent call last):
  File "pyvoicechanger.py", line 12, in <module>
    from PyQt5.QtCore import QProcess, Qt, QTimer
ModuleNotFoundError: No module named 'PyQt5'
```

**Comment by juancarlospaco** [comment]
We wont support Python2.
