### ISSUE TITLE
How can I make it so I don't hear the voice changer's output?

### ISSUE THREAD

**Issue by bengineer8** [juancarlospaco/pyvoicechanger#17]
kinda hard to talk when I can hear myself

**Comment by juancarlospaco** [comment]
I agree. :slightly_smiling_face: 
Turn down your headset volume.

**Comment by Strykar** [comment]
@juancarlospaco Is `wontfix` due to some limitation? This severely limits the usability of the app while gaming.

**Comment by juancarlospaco** [comment]
I really moved my development, including Python, to [Nim](https://nim-lang.org)
I would accept PR tho.
