### ISSUE TITLE
[i guess i found error in codes] ModuleNotFoundError: No module named 'PyQt5'

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [juancarlospaco/pyvoicechanger#19]
i'm debian 9 user & here is what i get

`esmailelbob@debian:/usr/local/bin$ python3.7 pyvoicechanger.py
Traceback (most recent call last):
  File "pyvoicechanger.py", line 12, in <module>
    from PyQt5.QtCore import QProcess, Qt, QTimer
ModuleNotFoundError: No module named 'PyQt5'`

**Comment by juancarlospaco** [comment]
[Requisites are on Requisites of the Readme](https://github.com/juancarlospaco/pyvoicechanger#requisites).
