### ISSUE TITLE
a lot of error's using pyvoicechanger

### ISSUE THREAD

**Issue by Axe-Usa** [juancarlospaco/pyvoicechanger#2]
error's:

> voicechanger.py
> Logger created with Log file at: C:\Users\Androide\AppData\Local\Temp\pyvoicecha
> nger.log.
> PyVoiceChanger.1.0.0https://github.com/juancarlospaco/pyvoicechanger#pyvoicechan
> ger
> Python 3.5.0 on Windows-7-6.1.7601-SP1.
> STDIN Encoding: cp850.
> STDERR Encoding: cp850.
> STDOUT Encoding:cp850
> Default Encoding: utf-8.
> FileSystem Encoding: mbcs.
> PYTHONIOENCODING Encoding: None.
> [WinError 126] The specified module could not be found
> Creating Abstract UDP Socket Lock for Single Instance.
> Socket Lock for Single Instance: <socket.socket fd=356, family=AddressFamily.AF_
> INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 8888)>.
> QSystemTrayIcon::setVisible: No Icon set
> Preparing Simple Post-Execution Messages.
> 'killall' is not recognized as an internal or external command,
> operable program or batch file.
> 'killall' is not recognized as an internal or external command,
> operable program or batch file.
> 'killall' is not recognized as an internal or external command,
> operable program or batch file.
> 'killall' is not recognized as an internal or external command,
> operable program or batch file.
> 'killall' is not recognized as an internal or external command,
> operable program or batch file.
> 'killall' is not recognized as an internal or external command,
> operable program or batch file.
> 'killall' is not recognized as an internal or external command,
> operable program or batch file.
> Voice Deformation Value: 1100
> Voice Deformation Command: play -q -V0 "|rec -q -V0 -n -d -R riaa bend pitch 110
> 0 "
> Minimizing Main Window to System TrayIcon now...

**Comment by juancarlospaco** [comment]
https://github.com/juancarlospaco/pyvoicechanger#requisites

Linux only.
