### ISSUE TITLE
anglerfish?

### ISSUE THREAD

**Issue by Zibri** [juancarlospaco/pyvoicechanger#9]
$ pip install anglerfish
Collecting anglerfish
  Downloading anglerfish-2.5.0-py2.py3-none-any.whl (49kB)
    100% |████████████████████████████████| 51kB 414kB/s 
Installing collected packages: anglerfish
Successfully installed anglerfish-2.5.0
zibri@zibrixnb:~$ pyvoicechanger.py 
Traceback (most recent call last):
  File "/usr/local/bin/pyvoicechanger.py", line 19, in <module>
    from anglerfish import (check_encoding, make_logger, make_post_exec_msg,
ModuleNotFoundError: No module named 'anglerfish'

**Comment by Jakecheslekov** [comment]
I dunno if this guy is still maintaining this project or not as he hasn't replied to my near month old ticket.
I ended up managing to get anglerfish installed but after I got past that error I end up with this error..
Traceback (most recent call last):
  File "/usr/bin/pyvoicechanger.py", line 19, in <module>
    from anglerfish import (check_encoding, make_logger, make_post_exec_msg,
  File "/usr/lib/python3.6/site-packages/anglerfish-3.0.0-py3.6.egg/anglerfish/__init__.py", line 51, in <module>
ImportError: cannot import name 'get_random_pasteldark_color'

**Comment by Jakecheslekov** [comment]
You COULD try installing it from the source github repo.
https://github.com/juancarlospaco/anglerfish

**Comment by Devp00l** [comment]
Same error here :(

**Comment by snqlby** [comment]
sudo pip install -Iv anglerfish==2.2.0

**Comment by Punksolid** [comment]
I just used sudo pip install anglerfish. But gave another error

**Comment by juancarlospaco** [comment]
Fixed on Master.
